### ISSUE TITLE
테스트용 이슈 생성

### ISSUE THREAD

**Issue by jeon-seun** [Cha-Young-Ho/TogetherSports#317]
# 신규 기능 명 (e.g 사용자 검색 기능)

> 기능이 어떤일을 하는지에 대한 설명 <br>(e.g 사용자 검색은 특정 값으로 사용자를 찾아 해당 사용자 정보 반환한다.)

## 새 기능

- **_새로운 기능에 대한 설명 예시_**

1. 사용자를 이름으로 검색할 수 있는 기능
2. 사용자를 이메일 주소로 검색할 수 있는 기능

## 구현 배경

- **_새로운 기능을 구현해야하는 이유와 사용될 상황 예시_**

### 구현 이유

- 다른 사용자와 관련된 기능 이용시 ID 값을 이용하는데 이 ID 값은 일반적으로 사용자가 알수 있거나 외울 수 있는 값이 아니기 때문에 사용자 정보를 일반 사용자가 알 수 있는 값으로 부터 얻어낼 수 있어야 한다. (구현 이유)

### 적용 상황

- 친구 등록 시 필요한 사용자 정보를 사용자 검색을 통해 얻을 때
- 팀 회원 추가시 필요한 사용자 정보를 사용자 검색을 통해 얻을 때

# 구현 방향

**_사용해야할 기술, 구현 방향성 제시 및 주의사항 명시_**<br>
사용자가 입력한 특정 검색 키 값에 부합하는 사용자를 DB 에서 조회하도록 구현

## 주의 사항

- **_기능 구현시 고려해야할 주의 사항_**

1. 동명이인, 같은 이메일 허용 등에 의해 사용자 검색 결과는 0 ~ N 개의 값을 지닐 수 있으므로 검색 결과는 리스트로 반환되어야 한다.
2. 검색 결과가 없는 경우 비어있는 리스트가 반환되어야 한다.
3. 반드시 하나 이상의 검색 키가 있어야 한다. 검색키가 없는 경우 검색하지 않는다.

## Todo

- **_기능 구현을 위한 소작업_**
- [ ] 검색 SQL 작성
- [ ] 검색어 유무 검증
- [ ] 사용자 검색 결과 DTO 정의
- [x] todo ...
- [ ] todo ...

## 관련 기술

**_구현 시 사용 또는 참고할 기술이나 사이트 (선택사항)_**

- [QueryDSL](http://querydsl.com)
- [Spring Data JPA](https://spring.io/projects/spring-data-jpa)
