### ISSUE TITLE
[Feature] 행정구역 정보 REST API

### ISSUE THREAD

**Issue by jeon-seun** [Cha-Young-Ho/TogetherSports#322]
# 행정구역 정보 REST API

> 특정 행정구역 내에 속하는 도, 시, 군, 구, 동 정보등을 제공하는 API

## 새 기능

1. 특정 행정구역 아래에 속하는 행정구역 목록을 조회할 수 있는 기능
2. 별도의 검색 키가 없는 경우 가장 큰 단위의 행정구역을 조회하는 기능

### 구현 이유

- 지도를 통한 주소를입력 시 초기 지도 위치에 따른 불편함이 있다.
- 지도를 통한 주소 입력 시 정확한 위치 표현에 대한 문제점이 있을 수 있다.
- 주소 직접 입력 시 긴 문자열 입력에 의한 불편함이 있다.
- 주소 직접 입력 시 입력된 주소값의 검증에 대한 문제점이 있을 수 있다.
- 행정구역 단위별로 선택할 수 있도록 UI를 구성하기 위해서는 행정구역 단위별로 하위 행정구역을 제공하는 API 가 필요하다.

### 적용 상황

- 방 생성 또는 회원정보 입력시 활동 지역 선택에 행정구역 단위별로 주소를 입력하도록 드랍다운을 구성할 때 사용
- 추후 주소 정보를 입력하는 모든 기능에 사용될 수 있다.

## 구현 방향

- 행정구역 정보 파일의 값을 읽어 상위/하위 행정구역을 구분하고 DB 에 계층 구조로 저장한 뒤 사용한다.
- 특정 행정구역의 하위 행정구역 조회 요청에 대해 DB self join 을 통해 정보를 가져오도록 구성한다.

### 주의 사항

1. API 요청 시 특정 행정구역에 대한 정보가 없는 경우 대한민국 행정구역 단위중 큰 단위 목록을 반환한다. (e.g 도, 특별시, 광역시)
2. 하위 행정구역 조회 시 해당 행정구역의 하위 행정구역이 없는 경우 API 응답 본문에서 하위 행정구역이 없는 것을 명시해야 한다. 
3. 행정구역 정보가 있는 파일에서 값을 읽어 DB 에 저장하는 행위는 DB 에 해당 정보가 없을 때만 실행하며 백엔드 서버를 실행할 때 수행해야 한다.

### Todo

- [x] 행정구역 정보 xlsx 파일 읽기
- [x] 단일 행정구역 데이터 자바 클래스로 변환
- [x] 행정구역간 계층 구조 설정
- [x] 데이터베이스에 행정구역 정보 저장
- [x] 서버 실행 시 행정구역에서 데이터 저장하도록 설정
- [x] 서버 실행 시 행정구역 데이터 저장 여부 확인
- [x] SQL self join 쿼리 작성
- [x] Rest API 구현
- [x] API 명세서 작성

### 관련 기술

- [POI](https://poi.apache.org)
- [Spring JdbcTemplate](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#jdbc-JdbcTemplate)
