### ISSUE TITLE
[Feature] 메인 페이지 애니메이션 구현

### ISSUE THREAD

**Issue by sagongjieun** [Cha-Young-Ho/TogetherSports#340]
# 메인 페이지 애니메이션 구현

> 산정된 디자인에 따른 메인페이지의 애니메이션 구현이 필요함 <br>

## 구현 요소

1. 방 생성하기 버튼의 하단 플로팅 고정 기능
2. 스크롤 위치에 따른 요소들의 fadein 기능
3. 다양한 종목들의 carousel slide 기능
4. 방 개수 집계판의 효과적인 애니메이션 기능

## 구현 배경

- **_새로운 기능을 구현해야하는 이유와 사용될 상황 예시_**

### 구현 이유

- 메인페이지는 사용자에게 전체 홈페이지에 대한 첫인상을 남겨주는 화면이므로 다양한 애니메이션 효과를 통해 재미 요소를 줄 수 있음

### 적용 상황

- 방 생성하기 플로팅 버튼의 경우 사용자의 스크롤 위치와 상관없이 언제 어디서든 "방 생성" 이라는 기능에 접근할 수 있게 하단에 고정시킴

# 구현 방향

- 라이브러리를 활용하지 않고 구현
- 산정된 디자인 결과와 요구된 애니메이션에 맞게 linkid.pw 사이트를 참고하여 구현

## Todo

- **_기능 구현을 위한 소작업_**
- [x] 방 생성하기 하단 플로팅
- [x] 요소들 fadein 적용
- [x] carousel slide 구현

## 관련 기술

**_구현 시 사용 또는 참고할 기술이나 사이트_**

- [CSS Animations](https://www.w3schools.com/css/css3_animations.asp)
- [CSS transform](https://developer.mozilla.org/ko/docs/Web/CSS/transform)
- 추가 예정
