### ISSUE TITLE
[Feature] 지역 추가 기능

### ISSUE THREAD

**Issue by MoveRoad** [Cha-Young-Ho/TogetherSports#342]
# 지역 추가 기능

> 세 단계의 지역을 선택하고, 선택된 지역을 통해 방을 필터링 할 수 있는 정보를 추가한다.

## 지역 추가 모달

1. 시/군/구에서 원하는 지역을 선택합니다.
2. 해당하는 지역에 하위 지역이 렌더되고, 마찬가지로 선택합니다.
3. 이렇게 총 세개의 지역을 선택하면 해당 지역이 저장됩니다.
4. 선택한 지역은 중복될 수 없으며, n개 까지만 선택할 수 있습니다.
5. 완료 버튼을 누르면 모달 창이 꺼지며, 선택했던 지역이 필터링에 추가됩니다.

## 구현 배경

- 사용자가 늘어가면서 방이 무수히 많아진다면 원하는 방을 찾기가 매우 어려워지게 되어 필터링이 필요하고
- 그 중 하나의 기능입니다.

### 구현 이유

- 구현 배경과 마찬가지로 원하는 방을 추려서 확인하기 위해 필요합니다.

### 적용 상황

- 방 목록에서 특정 지역을 정해 방을 확인하고 싶을 때

# 구현 방향

**_사용해야할 기술, 구현 방향성 제시 및 주의사항 명시_**<br>
- 선택한 지역은 중복될 수 없으며, 최대 n개 까지만 선택할 수 있습니다.
- 필터링에 추가되는 조건은 "완료" 버튼을 눌러야합니다.
- 현재 선택하고 있는 목록에 대한 강조를 표현해야 합니다.

## 주의 사항

- **_기능 구현시 고려해야할 주의 사항_**

1. 중복과 최댓 값만 고려해주면 됩니다.

## Todo

- **_기능 구현을 위한 소작업_**
- [x] UI/UX 작업
- [x] 지역 별 API 호출
- [x] 각 버튼 별 메소드
- [x] 주의 사항에 대한 예외처리
- [x] 상태 관리 라이브러리를 이용해 데이터 처리

## 관련 기술

**_구현 시 사용 또는 참고할 기술이나 사이트 (선택사항)_**
