### ISSUE TITLE
[Feature] 사용자 오프라인, 온라인 기능 추가

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#478]
# 신규 기능 명 (e.g 사용자 검색 기능)

> - 오프라인 : 어떠한 사용자가 웹 소켓에서 끊어졌을 경우 (방 나가기 제외) 타 사용자가 해당 사용자는 방에 존재하지 않다는 것을 보여주기 위한 기능 필요 
> - 온라인 : 사용자가 소켓에 연결되어있을 경우, 해당 사용자가 방에 존재한다는 것을 보여주기위한 기능 필요

## 새 기능

1. 온라인
2. 오프라인

### 적용 상황

- 온라인 : 소켓에 연결되었을 경우 방에 존재하는 사용자 온라인 표시가 있어야 함
- 오프라인 : 소켓에 끊겼을 경우 (타임아웃, 브라우저 탈출 및 기타) 사용자 오프라인 표시가 있어야 함

# 구현 방향

- 온라인 : 기존에 존재하는 connect, subscribe 과정 후 메세지를 서버로 요청
- 오프라인
  - 브라우저 탈출 : 탈출 전 서버에 message publish
  - 타임아웃 : 타임아웃 전 서버에 message publish
  - 기타 : 기타 상황 전 서버에 message publish

## Todo

- **_기능 구현을 위한 소작업_**
- [x] 온라인 WS 메세지 포맷 정하기(온라인은 필요없을 수 있음)
- [x] 오프라인 WS 메세지 포맷 정하기
- [x] 온라인 Message Code 정하기
- [x] 오프라인 Message Code 정하기

**Comment by Cha-Young-Ho** [comment]
# 오프라인 응답 Code 상정완료
Code : 1215
Message : 사용자가 오프라인이 되었습니다.

[✅ Notion Code 명세서](https://candied-literature-ad0.notion.site/Response-Code-3766426572c44e519193f2d89087949a)

**Comment by Cha-Young-Ho** [comment]
# 온라인 응답 Code 상정완료

_**Header**_
Code : 1509
Message : 사용자가 온라인이 되었습니다.

_**Body**_
userId : ~
userNIckname: ~

**Comment by Cha-Young-Ho** [comment]
기능 구현 완료
